### ISSUE TITLE
Mark repo as obsolete

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde.build#10]
We should mark this repo as obsolete. Anyone knows if Github or the Eclipse project has a standard for this?

**Comment by akurtakov** [comment]
I think it's https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by vogella** [comment]
@vik-chand can you do this as project lead? I cannot access the settings.

**Comment by sravanlakkimsetti** [comment]
> We should mark this repo as obsolete. Anyone knows if Github or the Eclipse project has a standard for this?

Because older versions 4.23 and below still require these repositories. We should not archive these yet. 4.23 is will go out of support on April 2025 for IBM customers that is the earliest date we can consider these repositories for archival

**Comment by mickaelistria** [comment]
Just remove all content from master, and keep only the README saying repo is obsolete and where to get the content. That should make things visible enough.

**Comment by vik-chand** [comment]
> can you do this as project lead? I cannot access the settings.

Even I don't have the permissions.

**Comment by vogella** [comment]
Anyway we cannot archive it for now, as maintenance work might be necessary. Closing this issue, I will push at some point a removal PR for master to keep only readme as @mickaelistria suggested.
